async function runRAGQuery(query, apiKey) {
    try {
        // 1. Fetch Knowledge Base
        const kbResponse = await fetch('data/knowledge-base.json');
        if (!kbResponse.ok) {
            throw new Error("Could not load knowledge-base.json. Verify file location.");
        }
        const kbData = await kbResponse.json();

        // 2. Perform Keyword Search across modules
        const lowerQuery = query.toLowerCase();
        let contextMatches = [];

        if (Array.isArray(kbData)) {
            kbData.forEach(module => {
                const title = module.title || "";
                const content = module.content || module.description || JSON.stringify(module);
                if (title.toLowerCase().includes(lowerQuery) || content.toLowerCase().includes(lowerQuery)) {
                    contextMatches.push(`[${title}]: ${content}`);
                }
            });
        }

        // Fallback context if no explicit keyword match is found
        const contextText = contextMatches.length > 0 
            ? contextMatches.join("\n\n") 
            : JSON.stringify(kbData).substring(0, 3000);

        // 3. Build Grounded Prompt
        const systemPrompt = `You are the AI Fluency Master Assistant. Use ONLY the following provided context to answer the user's question accurately.

CONTEXT FROM COURSE:
${contextText}

USER QUESTION: ${query}`;

        // 4. Call Gemini API endpoint
        
const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey.trim()}`;

        const apiResponse = await fetch(endpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{ text: systemPrompt }]
                }]
            })
        });

        const data = await apiResponse.json();

        if (!apiResponse.ok) {
            console.error("Gemini API Error Response:", data);
            throw new Error(data.error?.message || "Invalid API response from Gemini.");
        }

        const reply = data.candidates?.[0]?.content?.parts?.[0]?.text 
            || "No output generated by the model.";

        return {
            text: reply,
            sources: contextMatches.length > 0 ? ["Course Knowledge Base"] : []
        };

    } catch (error) {
        console.error("RAG Execution Error:", error);
        throw error;
    }
}
